FROM hyperledger/fabric-peer
RUN rm /bin/sh && ln -s /bin/bash /bin/sh
RUN sed -i "s@http://.*archive.ubuntu.com@http://mirrors.tuna.tsinghua.edu.cn@g" /etc/apt/sources.list && \
    sed -i "s@http://.*security.ubuntu.com@http://mirrors.tuna.tsinghua.edu.cn@g" /etc/apt/sources.list && \
    apt-get update && \
    apt-get install -y \
    vim \
    net-tools \
    tree \
    gcc \
    g++ \
    p7zip-full \
    frr \
    iputils-ping

# 配置frr
COPY resources/daemons /etc/frr/daemons

# 开启ipv4转发
RUN echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf && \
    sysctl -p

ENV TZ "Asia/Shanghai"
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata && \
    echo $TZ > /etc/timezone && \
    ln -fs /usr/share/zoneinfo/$TZ /etc/localtime && \
    dpkg-reconfigure tzdata -f noninteractive
